version: '3.8'
services:
  pg_db:
    container_name: pgDB
    image: postgres:15.4
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: yapp-db
      POSTGRES_USER: sam
      POSTGRES_PASSWORD: letsGetStarted
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - '5432:5432'
    volumes:
      - ./pg_db/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d$${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis_chatroom:
     container_name: rdChat
     image: redis
     expose:
       - 6379
     ports: 
        - '6379:6379'
  redis_inbox:
     container_name: rdInbox
     image: redis
     expose:
       - 6379
     ports: 
        - '6380:6379'

